apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAsqHuaMmNEQ/Ngi5kb1gEb+LF091cncCwmNechNZrJZ4EZFbyOI+/lrfcBkSK+INI4fAarlZ8qb73NRYOBdFQv26KWV/5ToZusQWTYW2Q9mAo+kouUVdLNHE3qZMgl3Pw5BNExyIUUlXhJCOMnklWF8J65nEd2me493kuECxL6b1wJ+IRXrHHGzPCfdJ9RnomxJjh8tga4WzagOioWUHxIhoLepGjyX6aZFZDnkOP1EudiZIinv6+CiYfiSr++/Gp/ypdyffL0CpZCApqhH0mUGUoiCxDJX1cReNu1acKysNFBzPxscE9IAixzZz4r32Lo4kDdgC1cMQEdGOVRx7LKR0WZZCgNVVI64kUW6iW2wz8xwG0hfa5ErVgQwWpRNT6WC17bvcErwK9xuFLwpxMwEF2BI+t8shJzdT3cT2LapMiMDM8HvAidi7YkIOk5t/dFe4HFzWPokh5yOFWScqAOsdcrBL+iJgDkanMm2XxCn7NbvXV5OHCa3nQcAvtyEzzeEgiPPuUHjCcqiIG2+FFdVzBTDqybCQcjZjynEtilZn5UZ3qKQxEJ8uCCQztgQPvoxqVuDUdj2ONvLrUFeX/z/wg8OFGX+KUWnbcRcvhga4iFaHsc265j8LA0Aj0CiUXDXXKulq3E9eHrP3hlheY+LUOHfDc8dAubw4qkagNbeg610Rvs9r3lTzGZRu/gsVbAcYZqu/SqG7TGgMFhhsXWmwldGnKokWJ/vrh+m1bG820U1aWxpkqP
    username: AgCxABIZ0pJ5A8Eon5BpWhrWhCFWdVqFLP5GGo0R8oBZD+IBtNg3v3tTiSU66oSbnv4TmFCWm8mj9YIJ8fCoWATN/nkpm8OMj6d/R1WEjzZqfL5942osTatpq47cAMKY0/c8elclGEYfnU8IWmet6BSh4m2VRFOCpiiaTi215Rbt4XCR4LepT0ZhYb9+SMPUyRYl8MlqhY7qeXH+0pQRMS7D4ha1HIQ89dU20v05c0w4p3vfLDia+B5gIjA+l79XEvicuORmphZxZKtOTQC/9J5XKBYWJkp1Ub6VJaDSJoO7yvpb8UL1tThvAqjgGMbUW1RXnuLGJew7l0IhKtMrI1D6hPbeGEmxYAaHpDpYr0V6dK8XphRTDRkT6cuu1aN1s0sj2dVQM1hB3cIVSEiAkNrVdhrU8Rw/Ny+A7b8v0Vn9JHh760ebxkWfFsk+Nsdt+xo6AAULyFFNW2DnZrU/W5UVOzulREUW+XPyNQ0iYRsKeFpblh6AkvfymxyGYGmGCIJ7Cm8cmDtSwy995qlG/PW/Jn9KWpzx4rJFDZ2NIoejT8QF/dfIit95+O+s4s8oIDv9mzn+M22O8aB4sUZZ4SRzNwas4O7HbfoIEmX4qtrbNtENKNDBlNlyvnTXhNGolUtklma/hA3+3ifrV8fRruMl6I2RvSGx1Xed93AGEsV9xpBJF7EEq2D9J81YNQxhDuLPzqCoKPMC2a8=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

